apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqlconfigmap
data:
  mysql_example.sql: |-
    DROP DATABASE IF EXISTS test;
    CREATE DATABASE test; 
  sample-file.sql : |
    {{- $.Files.Get "files/sample-test.sql" | indent 6 }}